namespace MaldaLang.Testing;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

public sealed class PropertyRegressionArtifactRequest
{
    public string SourcePath { get; init; } = string.Empty;
    public string PropertyName { get; init; } = "property";
    public int Seed { get; init; }
    public int Iterations { get; init; }
    public int FailedTrial { get; init; }
    public string Counterexample { get; init; } = "[]";
    public string ShrunkCounterexample { get; init; } = "[]";
    public string CanonicalCounterexamplePayload { get; init; } = "[]";
    public string? RecommendedRegressionPath { get; init; }
    public string? RecommendedRegressionFileName { get; init; }
}

public static class PropertyRegressionArtifactSupport
{
    public static bool TryExtractFromOutput(string output, out PropertyRegressionArtifactRequest? request)
    {
        request = null;
        if (string.IsNullOrWhiteSpace(output))
        {
            return false;
        }

        var trimmedOutput = output.Trim();
        if (TryParseCiPayload(trimmedOutput, out request))
        {
            return true;
        }

        foreach (var line in output.Split(new[] { "\r\n", "\n", "\r" }, StringSplitOptions.RemoveEmptyEntries))
        {
            var candidate = line.Trim();
            if (!candidate.StartsWith('{') || !candidate.EndsWith('}'))
            {
                continue;
            }

            if (TryParseCiPayload(candidate, out request))
            {
                return true;
            }
        }

        return false;
    }

    public static string BuildArtifactContent(PropertyRegressionArtifactRequest request)
    {
        var sourceNormalized = NormalizePath(request.SourcePath);
        var original = string.IsNullOrWhiteSpace(request.Counterexample) ? "[]" : request.Counterexample;
        var shrunk = string.IsNullOrWhiteSpace(request.ShrunkCounterexample)
            ? request.CanonicalCounterexamplePayload
            : request.ShrunkCounterexample;

        return string.Join(
            "\n",
            new[]
            {
                "// Auto-generated by IDE Create Regression action",
                $"// Source: {sourceNormalized}",
                $"// Property: {request.PropertyName}",
                $"// Seed: {request.Seed}",
                $"// Iterations: {request.Iterations}",
                $"// FailedTrial: {request.FailedTrial}",
                $"// Counterexample: {original}",
                $"// ShrunkCounterexample: {shrunk}",
                string.Empty,
                $"var regressionSource = \"{EscapeString(sourceNormalized)}\";",
                $"var regressionProperty = \"{EscapeString(request.PropertyName)}\";",
                $"var regressionSeed = {request.Seed};",
                $"var regressionIterations = {request.Iterations};",
                $"var regressionFailedTrial = {request.FailedTrial};",
                $"var regressionArgs = {request.CanonicalCounterexamplePayload};",
                "print(\"Regression artifact loaded:\");",
                "print(regressionSource + \"::\" + regressionProperty);",
                "print(regressionArgs);",
                string.Empty
            });
    }

    public static string BuildRecommendedFileName(PropertyRegressionArtifactRequest request)
    {
        var sourceSlug = Slugify(GetSourceStem(request.SourcePath));
        var propertySlug = Slugify(request.PropertyName);
        var stableHash = ComputeHash(
            $"{request.SourcePath}|{request.PropertyName}|{request.Seed}|{request.Iterations}|{request.FailedTrial}|{request.CanonicalCounterexamplePayload}");
        var baseName = $"{sourceSlug}-{propertySlug}-seed{request.Seed}-trial{request.FailedTrial}-{stableHash}";
        return $"{baseName}.spec.malda";
    }

    public static string EnsureSpecExtension(string fileName)
    {
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return "property-regression.spec.malda";
        }

        if (fileName.EndsWith(".spec.malda", StringComparison.OrdinalIgnoreCase))
        {
            return fileName;
        }

        if (fileName.EndsWith(".malda", StringComparison.OrdinalIgnoreCase))
        {
            var stem = Path.GetFileNameWithoutExtension(fileName);
            return $"{stem}.spec.malda";
        }

        return $"{fileName}.spec.malda";
    }

    public static string ResolveCollisionSafePath(string preferredPath, string content)
    {
        var fullPreferredPath = Path.GetFullPath(preferredPath);
        var directory = Path.GetDirectoryName(fullPreferredPath) ?? Directory.GetCurrentDirectory();
        var fileName = Path.GetFileName(fullPreferredPath);
        var extension = ".malda";
        string fileNameStem;
        if (fileName.EndsWith(".spec.malda", StringComparison.OrdinalIgnoreCase))
        {
            extension = ".spec.malda";
            fileNameStem = fileName[..^".spec.malda".Length];
        }
        else
        {
            extension = Path.GetExtension(fullPreferredPath);
            if (string.IsNullOrWhiteSpace(extension))
            {
                extension = ".malda";
            }

            fileNameStem = Path.GetFileNameWithoutExtension(fullPreferredPath);
        }

        Directory.CreateDirectory(directory);

        var attempt = 0;
        while (true)
        {
            var suffix = attempt == 0 ? string.Empty : $"-{attempt.ToString(CultureInfo.InvariantCulture)}";
            var candidate = Path.Combine(directory, $"{fileNameStem}{suffix}{extension}");
            if (!File.Exists(candidate))
            {
                return candidate;
            }

            var existing = File.ReadAllText(candidate);
            if (string.Equals(existing, content, StringComparison.Ordinal))
            {
                return candidate;
            }

            attempt++;
        }
    }

    public static string ResolveWorkspaceSafePreferredPath(
        PropertyRegressionArtifactRequest request,
        string workspaceDirectory)
    {
        var workspaceRoot = Path.GetFullPath(string.IsNullOrWhiteSpace(workspaceDirectory)
            ? Directory.GetCurrentDirectory()
            : workspaceDirectory);
        var fallbackFileName = BuildSafeFileName(request.RecommendedRegressionFileName, request);
        var fallbackPath = Path.Combine(workspaceRoot, "tests", "regressions", fallbackFileName);

        if (string.IsNullOrWhiteSpace(request.RecommendedRegressionPath))
        {
            return fallbackPath;
        }

        var safeRelativePath = TryBuildSafeRelativePath(request.RecommendedRegressionPath!);
        if (string.IsNullOrWhiteSpace(safeRelativePath))
        {
            return fallbackPath;
        }

        var candidate = Path.GetFullPath(Path.Combine(workspaceRoot, safeRelativePath));
        if (!IsPathWithinRoot(workspaceRoot, candidate))
        {
            return fallbackPath;
        }

        return EnsureSpecMaldaPath(candidate);
    }

    private static bool TryParseCiPayload(string payloadText, out PropertyRegressionArtifactRequest? request)
    {
        request = null;

        try
        {
            using var doc = JsonDocument.Parse(payloadText);
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                return false;
            }

            if (!root.TryGetProperty("mode", out var mode) ||
                !string.Equals(mode.GetString(), "ci", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            if (!root.TryGetProperty("action", out var action) ||
                !string.Equals(action.GetString(), "run", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            IEnumerable<JsonElement> candidates = Enumerable.Empty<JsonElement>();
            if (root.TryGetProperty("failures", out var failures) && failures.ValueKind == JsonValueKind.Array)
            {
                candidates = failures.EnumerateArray();
            }
            else if (root.TryGetProperty("results", out var results) && results.ValueKind == JsonValueKind.Array)
            {
                candidates = results.EnumerateArray();
            }

            foreach (var result in candidates)
            {
                if (!TryParseFailure(result, out request))
                {
                    continue;
                }

                return true;
            }
        }
        catch (JsonException)
        {
            return false;
        }
        catch (InvalidOperationException)
        {
            // Non-object roots (for example plain numbers in normal run output)
            // can throw when trying to read object properties.
            return false;
        }

        return false;
    }

    private static bool TryParseFailure(JsonElement result, out PropertyRegressionArtifactRequest? request)
    {
        request = null;
        if (result.ValueKind != JsonValueKind.Object)
        {
            return false;
        }

        if (!result.TryGetProperty("status", out var statusElement) ||
            !string.Equals(statusElement.GetString(), "failed", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (!result.TryGetProperty("property", out var property) || property.ValueKind != JsonValueKind.Object)
        {
            return false;
        }

        if (!result.TryGetProperty("isProperty", out var isPropertyElement) ||
            isPropertyElement.ValueKind != JsonValueKind.True)
        {
            return false;
        }

        if (!property.TryGetProperty("canGenerateRegression", out var canGenerateElement) ||
            canGenerateElement.ValueKind != JsonValueKind.True)
        {
            return false;
        }

        var canonicalPayload = GetOptionalString(property, "canonicalCounterexamplePayload");
        var shrunk = GetOptionalString(property, "shrunkCounterexample");
        var original = GetOptionalString(property, "counterexample");
        var canonical = FirstNonEmpty(canonicalPayload, shrunk, original, "[]");
        var recommendedPath = GetOptionalString(property, "recommendedRegressionPath");
        var recommendedFileName = GetOptionalString(property, "recommendedRegressionFileName");
        if (string.IsNullOrWhiteSpace(recommendedPath) && string.IsNullOrWhiteSpace(recommendedFileName))
        {
            return false;
        }

        var rawPath = GetOptionalString(result, "path") ?? string.Empty;
        var sourcePath = ExtractSourcePath(rawPath);
        var propertyName = FirstNonEmpty(GetOptionalString(result, "propertyName"), "property");

        request = new PropertyRegressionArtifactRequest
        {
            SourcePath = sourcePath,
            PropertyName = propertyName,
            Seed = GetOptionalInt(property, "seed"),
            Iterations = GetOptionalInt(property, "iterations"),
            FailedTrial = GetOptionalInt(property, "failedTrial"),
            Counterexample = FirstNonEmpty(original, "[]"),
            ShrunkCounterexample = FirstNonEmpty(shrunk, canonical),
            CanonicalCounterexamplePayload = canonical,
            RecommendedRegressionPath = recommendedPath,
            RecommendedRegressionFileName = recommendedFileName
        };
        return true;
    }

    private static bool IsPathWithinRoot(string rootPath, string candidatePath)
    {
        var normalizedRoot = EnsureTrailingSeparator(Path.GetFullPath(rootPath));
        var normalizedCandidate = Path.GetFullPath(candidatePath);
        return normalizedCandidate.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase);
    }

    private static string EnsureTrailingSeparator(string path)
    {
        if (path.EndsWith(Path.DirectorySeparatorChar) || path.EndsWith(Path.AltDirectorySeparatorChar))
        {
            return path;
        }

        return path + Path.DirectorySeparatorChar;
    }

    private static string BuildSafeFileName(string? requestedFileName, PropertyRegressionArtifactRequest request)
    {
        var candidate = string.IsNullOrWhiteSpace(requestedFileName)
            ? BuildRecommendedFileName(request)
            : requestedFileName!;
        candidate = Path.GetFileName(candidate);
        if (string.IsNullOrWhiteSpace(candidate))
        {
            candidate = BuildRecommendedFileName(request);
        }

        return EnsureSpecExtension(SanitizePathSegment(candidate));
    }

    private static string? TryBuildSafeRelativePath(string relativePath)
    {
        if (Path.IsPathRooted(relativePath))
        {
            return null;
        }

        var rawSegments = relativePath
            .Split(new[] { '/', '\\' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .ToList();
        if (rawSegments.Count == 0)
        {
            return null;
        }

        var sanitizedSegments = new List<string>(rawSegments.Count);
        foreach (var segment in rawSegments)
        {
            if (segment == "." || segment == "..")
            {
                return null;
            }

            var sanitized = SanitizePathSegment(segment);
            if (string.IsNullOrWhiteSpace(sanitized))
            {
                return null;
            }

            sanitizedSegments.Add(sanitized);
        }

        if (sanitizedSegments.Count == 0)
        {
            return null;
        }

        sanitizedSegments[^1] = EnsureSpecExtension(sanitizedSegments[^1]);
        return Path.Combine(sanitizedSegments.ToArray());
    }

    private static string SanitizePathSegment(string segment)
    {
        if (string.IsNullOrWhiteSpace(segment))
        {
            return "item";
        }

        var invalidChars = Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(segment.Length);
        foreach (var c in segment)
        {
            if (invalidChars.Contains(c))
            {
                builder.Append('-');
            }
            else
            {
                builder.Append(c);
            }
        }

        var sanitized = builder.ToString().Trim();
        while (sanitized.Contains("..", StringComparison.Ordinal))
        {
            sanitized = sanitized.Replace("..", ".", StringComparison.Ordinal);
        }

        sanitized = sanitized.Trim('.', ' ');
        return string.IsNullOrWhiteSpace(sanitized) ? "item" : sanitized;
    }

    private static string EnsureSpecMaldaPath(string path)
    {
        if (path.EndsWith(".spec.malda", StringComparison.OrdinalIgnoreCase))
        {
            return path;
        }

        if (path.EndsWith(".malda", StringComparison.OrdinalIgnoreCase))
        {
            return path[..^".malda".Length] + ".spec.malda";
        }

        return path + ".spec.malda";
    }

    private static string ExtractSourcePath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return "unknown";
        }

        var markerIndex = path.IndexOf("::", StringComparison.Ordinal);
        if (markerIndex < 0)
        {
            return path;
        }

        return path[..markerIndex];
    }

    private static string GetSourceStem(string sourcePath)
    {
        var fileName = Path.GetFileName(sourcePath);
        var stem = Path.GetFileNameWithoutExtension(fileName);
        if (stem.EndsWith(".test", StringComparison.OrdinalIgnoreCase) ||
            stem.EndsWith(".spec", StringComparison.OrdinalIgnoreCase))
        {
            stem = Path.GetFileNameWithoutExtension(stem);
        }

        return string.IsNullOrWhiteSpace(stem) ? "test" : stem;
    }

    private static string Slugify(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
        {
            return "item";
        }

        var builder = new StringBuilder(raw.Length);
        foreach (var c in raw)
        {
            if (char.IsLetterOrDigit(c))
            {
                builder.Append(char.ToLowerInvariant(c));
            }
            else
            {
                builder.Append('-');
            }
        }

        var collapsed = builder.ToString().Trim('-');
        while (collapsed.Contains("--", StringComparison.Ordinal))
        {
            collapsed = collapsed.Replace("--", "-", StringComparison.Ordinal);
        }

        return string.IsNullOrWhiteSpace(collapsed) ? "item" : collapsed;
    }

    private static string ComputeHash(string raw)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(raw));
        var hex = Convert.ToHexString(bytes);
        return hex[..12].ToLowerInvariant();
    }

    private static int GetOptionalInt(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value))
        {
            return 0;
        }

        if (value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out var parsed))
        {
            return parsed;
        }

        return 0;
    }

    private static string? GetOptionalString(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var value))
        {
            return null;
        }

        if (value.ValueKind == JsonValueKind.Null)
        {
            return null;
        }

        return value.GetString();
    }

    private static string FirstNonEmpty(params string?[] values)
    {
        foreach (var value in values)
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                return value;
            }
        }

        return string.Empty;
    }

    private static string EscapeString(string raw)
    {
        return raw
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('\\', '/');
    }
}
